language: python

sudo: false

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
    - python: 2.7
      env: TOXENV=py27

install:
  - pip install -U setuptools tox
  - pip install -e .
  - pip install pytest-cov codecov -r tests/requirements.txt

script:
  - tox

after_success:
  - py.test tests/ example/ --cov=./
  - codecov
